"""Operational contracts for the Forge automation pipeline."""

from .contracts import (
    CheckRun,
    ContractError,
    CRITIC_RESULT_OPTIONAL_FIELDS,
    CRITIC_RESULT_REQUIRED_FIELDS,
    CriticResult,
    ExecutorResult,
    PipelineStage,
    PullRequestSnapshot,
    REVIEWER_RESULT_OPTIONAL_FIELDS,
    REVIEWER_RESULT_REQUIRED_FIELDS,
    ReviewerResult,
    RunRecord,
    StageOutcome,
    StageResult,
    TaskRecord,
    parse_stage_result,
    transition_digest,
    validate_stage_result_binding,
)

__all__ = [
    "CheckRun",
    "ContractError",
    "CRITIC_RESULT_OPTIONAL_FIELDS",
    "CRITIC_RESULT_REQUIRED_FIELDS",
    "CriticResult",
    "ExecutorResult",
    "PipelineStage",
    "PullRequestSnapshot",
    "REVIEWER_RESULT_OPTIONAL_FIELDS",
    "REVIEWER_RESULT_REQUIRED_FIELDS",
    "ReviewerResult",
    "RunRecord",
    "StageOutcome",
    "StageResult",
    "TaskRecord",
    "parse_stage_result",
    "transition_digest",
    "validate_stage_result_binding",
]
